
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDOTDIVIDEleftPOWERleftTRANSPINVERSEDIVIDE DOT INVERSE LPAREN MATRIX MINUS NUMBER PLUS POWER RPAREN SCALAR TIMES TRANSP VECTORstatement : expressionexpression : LPAREN expression RPAREN\n    expression : expression TRANSP\n    expression : expression PLUS expression\n       | expression MINUS expression\n       | expression TIMES expression\n       | expression DOT expression\n       | expression DIVIDE expression\n       | expression POWER expression\n\n                  expression : SCALAR LPAREN expression RPARENexpression : INVERSE expression\n    expression : MATRIX\n                 | SCALAR\n                 | NUMBER\n                 | VECTOR\n    '
    
_lr_action_items = {'LPAREN':([0,3,4,5,10,11,12,13,14,15,17,],[3,3,17,3,3,3,3,3,3,3,3,]),'SCALAR':([0,3,5,10,11,12,13,14,15,17,],[4,4,4,4,4,4,4,4,4,4,]),'INVERSE':([0,3,5,10,11,12,13,14,15,17,],[5,5,5,5,5,5,5,5,5,5,]),'MATRIX':([0,3,5,10,11,12,13,14,15,17,],[6,6,6,6,6,6,6,6,6,6,]),'NUMBER':([0,3,5,10,11,12,13,14,15,17,],[7,7,7,7,7,7,7,7,7,7,]),'VECTOR':([0,3,5,10,11,12,13,14,15,17,],[8,8,8,8,8,8,8,8,8,8,]),'$end':([1,2,4,6,7,8,9,18,19,20,21,22,23,24,25,27,],[0,-1,-13,-12,-14,-15,-3,-11,-4,-5,-6,-7,-8,-9,-2,-10,]),'TRANSP':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[9,-13,-12,-14,-15,-3,9,-11,9,9,9,9,9,9,-2,9,-10,]),'PLUS':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[10,-13,-12,-14,-15,-3,10,-11,-4,-5,-6,-7,-8,-9,-2,10,-10,]),'MINUS':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[11,-13,-12,-14,-15,-3,11,-11,-4,-5,-6,-7,-8,-9,-2,11,-10,]),'TIMES':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[12,-13,-12,-14,-15,-3,12,-11,12,12,-6,-7,-8,-9,-2,12,-10,]),'DOT':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[13,-13,-12,-14,-15,-3,13,-11,13,13,-6,-7,-8,-9,-2,13,-10,]),'DIVIDE':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[14,-13,-12,-14,-15,-3,14,-11,14,14,-6,-7,-8,-9,-2,14,-10,]),'POWER':([2,4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[15,-13,-12,-14,-15,-3,15,-11,15,15,15,15,15,-9,-2,15,-10,]),'RPAREN':([4,6,7,8,9,16,18,19,20,21,22,23,24,25,26,27,],[-13,-12,-14,-15,-3,25,-11,-4,-5,-6,-7,-8,-9,-2,27,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,5,10,11,12,13,14,15,17,],[2,16,18,19,20,21,22,23,24,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','met.py',69),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','met.py',79),
  ('expression -> expression TRANSP','expression',2,'p_transp','met.py',84),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binoper','met.py',97),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binoper','met.py',98),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binoper','met.py',99),
  ('expression -> expression DOT expression','expression',3,'p_expression_binoper','met.py',100),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binoper','met.py',101),
  ('expression -> expression POWER expression','expression',3,'p_expression_binoper','met.py',102),
  ('expression -> SCALAR LPAREN expression RPAREN','expression',4,'p_expression_call','met.py',116),
  ('expression -> INVERSE expression','expression',2,'p_expression_uminus','met.py',130),
  ('expression -> MATRIX','expression',1,'p_expression_matrix','met.py',147),
  ('expression -> SCALAR','expression',1,'p_expression_matrix','met.py',148),
  ('expression -> NUMBER','expression',1,'p_expression_matrix','met.py',149),
  ('expression -> VECTOR','expression',1,'p_expression_matrix','met.py',150),
]
